version: '3.3'

services:
  web:
    build: .
    command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=development
      - NEW_SECRET_KEY=p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_jD92ktaSSbUIetFLyadwckJA00FEiopPLV
      - STRIPE_TEST_SECRET_KEY=sk_test_zFLGUB9p0S2DsnMbUMSrmbrf00wHNdRd7x
    volumes:
    - .:/code
    ports:
    - 8000:8000
    depends_on:
    - db
  db:
    image: postgres:11
    volumes:
    - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
